spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      authentication-database: admin
      port: 27017
      host: localhost
      username: myuser
      password: mypwd
