spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      authentication-database: admin
      port: 27017
      host: ${MONGODB_URL_CONNECTION}
      username: myuser
      password: mypwd
